# Generated by Django 3.1.6 on 2021-05-31 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210530_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item_json',
            new_name='items_json',
        ),
    ]
